name: sacheonseong_game
description: "A standalone Sacheonseong game project."
publish_to: 'none'
version: 1.2.0+64

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  audioplayers: ^6.5.1
  firebase_core: ^4.4.0
  cloud_firestore: ^6.1.2
  shared_preferences: ^2.2.2
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/image/
    - assets/image/tiles/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/image/icon.png"
  min_sdk_android: 21
